import os

SECRET_KEY = os.environ["SUPERSET_SECRET_KEY"]
SQLALCHEMY_DATABASE_URI = os.environ["SUPERSET_METADATA_DB_URI"]

ENABLE_PROXY_FIX = True
PREFERRED_URL_SCHEME = "http"

ROW_LIMIT = 5000
SQL_MAX_ROW = 100000
